try:
    from .kling_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
except ImportError:
    # Standalone (pytest / direct script) import path.
    from kling_nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS

try:
    from .kling3_full import (
        NODE_CLASS_MAPPINGS as KLING3_FULL_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as KLING3_FULL_NODE_DISPLAY_NAME_MAPPINGS,
    )
except ImportError:
    from kling3_full import (
        NODE_CLASS_MAPPINGS as KLING3_FULL_NODE_CLASS_MAPPINGS,
        NODE_DISPLAY_NAME_MAPPINGS as KLING3_FULL_NODE_DISPLAY_NAME_MAPPINGS,
    )

NODE_CLASS_MAPPINGS.update(KLING3_FULL_NODE_CLASS_MAPPINGS)
NODE_DISPLAY_NAME_MAPPINGS.update(KLING3_FULL_NODE_DISPLAY_NAME_MAPPINGS)

__all__ = ["NODE_CLASS_MAPPINGS", "NODE_DISPLAY_NAME_MAPPINGS"]
